### ISSUE TITLE
Sobre peamarelle

### ISSUE THREAD

**Issue by delucas** [PrograAvanzadaPick60/jrpg#2]
https://github.com/peamarelle no debería formar parte del grupo, si abandonó la materia.
Por favor, removerlo de la organización y del README.

/cc @JonaDeDonato

**Comment by JonaDeDonato** [comment]
Ya lo removí de la organización, apenas actualicemos el README, lo removemos también de ahi.

**Comment by delucas** [comment]
:+1:
